#include "DPN_PacketType.h"




const char *packetTypeName(DPN_PacketType t) {
    switch (t) {
    GET_NAME(DPN_PACKETTYPE__NO_TYPE);
    GET_NAME(DPN_PACKETTYPE__TEXT_MESSAGE);
    GET_NAME(DPN_PACKETTYPE__HASH_SUM);
    GET_NAME(DPN_PACKETTYPE__SYNC);
    GET_NAME(DPN_PACKETTYPE__FILE_PACKET);
    GET_NAME(DPN_PACKETTYPE__REGISTER_FAST_FILE);
    GET_NAME(DPN_PACKETTYPE__REQUEST_FILE);
    GET_NAME(DPN_PACKETTYPE__TRANSMIT_ANSWER);
    GET_NAME(DPN_PACKETTYPE__FILE_TRANSMIT_PREPARE);
    GET_NAME(DPN_PACKETTYPE__PING);
    GET_NAME(DPN_PACKETTYPE__REQUEST);
    GET_NAME(DPN_PACKETTYPE__LOCAL_ENVIRONMENT);
    GET_NAME(DPN_PACKETTYPE__INVALID_TYPE);
    GET_NAME(DPN_PACKETTYPE__MAKE_SHADOW_CONNECTION);
    GET_NAME(DPN_PACKETTYPE__USER_TYPE);
    GET_NAME(DPN_PACKETTYPE__MEDIA_ANSWER);
    GET_NAME(DPN_PACKETTYPE__MEDIA_STREAM_PREPARE);


    default: return "[NO TYPE]";
    }
}
uint32_t packetMaxSize(DPN_PacketType t) {

    DPN_SETTINGS_MARK

    switch (t) {
    case DPN_PACKETTYPE__FILE_PACKET: return DPN_DEFAULT_MAX_FILE_PACKET_SIZE;
    default: return DPN_DEFAULT_MAX_PACKET_SIZE;
    }
}
bool packetSupportEmptySize(DPN_PacketType t) {

    DPN_SETTINGS_MARK

    switch (t) {
//    case DPN_PACKETTYPE__VIDEO_STREAM_PREPARE: return true;
    default: return false;
    }
}
